name: Integrity check

on: push # [push, pull_request]

jobs:
  build:
    runs-on: windows-latest #ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: |
        python3 -m pip install --upgrade pipenv

    - name: Initialise pipenv
      # This could be any pipenv command, but this might be useful for
      # debugging.
      run: |
        pipenv lock -r

    - name: Install pure dulwich
      shell: bash
      run: |
        pipenv run pip install -r <(pipenv lock -r | sed -En 's/(^dulwich==.+$)/\1 --global-option=--pure/p')

    - name: Install dependencies
      shell: bash
      run: |
        pipenv install --dev

    # TODO Run tests separately?
    - name: Run tests
      run: |
        pipenv run mamba ./
