name: Release beta

on:
  push:
    # TODO s/experiment/beta/
    tags:
      - 'v[0-9]+.[0-9]+-experiment*'
      - 'v[0-9]+.[0-9]+.[0-9]+-experiment*'
    # e.g. v0.9-experiment.0.0

jobs:
  release_beta:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: |
        python3 -m pip install --upgrade pipenv

    - name: Install PyQt5 for pyuic5
      shell: bash
      run: |
        python3 -m pip install PyQt5

    - name: Package plugin
      run: |
        ./package_plugin.sh
